---
apiVersion: v1
kind: Service
metadata:
  name: songs-db
  namespace: dev
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: songs-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db
  namespace: dev
spec:
  serviceName: songs-db
  replicas: 1
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: songs-db
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "exec pg_isready -h localhost -U postgres"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: songs-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: songs-db-storage
      spec:
        storageClassName: hostpath
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: resources-db
  namespace: dev
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: resources-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: dev
spec:
  serviceName: resources-db
  replicas: 1
  selector:
    matchLabels:
      app: resources-db
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: resources-db
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "exec pg_isready -h localhost -U postgres"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: resources-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: resources-db-storage
      spec:
        storageClassName: hostpath
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
