---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-service-deployment
  namespace: dev
  labels:
    app: songs-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-service
  template:
    metadata:
      labels:
        app: songs-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nslookup songs-db; do echo waiting for songs-db; sleep 2; done' ]
      containers:
        - name: songs-service
          image: songs-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://songs-db:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: songs-storage
              mountPath: /app/data
      volumes:
        - name: songs-storage
          persistentVolumeClaim:
            claimName: songs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: dev
  labels:
    app: songs-service
spec:
  type: NodePort
  selector:
    app: songs-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001