---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-ms
  namespace: dev
  labels:
    app: songs-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-ms
  template:
    metadata:
      labels:
        app: songs-ms
    spec:
      enableServiceLinks: false
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nslookup songs-db; do echo waiting for songs-db; sleep 2; done' ]
      containers:
        - name: songs-ms
          image: songs-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_DB_URL
              value: "songs-db"
          volumeMounts:
            - name: songs-storage
              mountPath: /app/data
      volumes:
        - name: songs-storage
          persistentVolumeClaim:
            claimName: songs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: songs-ms
  namespace: dev
  labels:
    app: songs-ms
spec:
  type: NodePort
  selector:
    app: songs-ms
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001